import logging
from .base_node import (
    SupersideFalNode,
    APIClientMixin,
    VideoProcessingMixin,
    API_KEY_INPUT_SPEC,
)

logger = logging.getLogger(__name__)


class SupersideGeminiOmniFlashEditNode(
    SupersideFalNode,
    VideoProcessingMixin,
    APIClientMixin,
):
    """
    Gemini Omni Flash Edit Node: Edit an existing video using Google's
    Gemini Omni Flash via fal.ai API.

    Takes a source video and a simple text instruction describing the
    change (e.g. "Make this video anime. Keep everything else the same.").

    Limitations (from the model provider): editing uploaded videos is not
    available in the EEA, Switzerland, or the United Kingdom; voice editing
    is not supported; audio references cannot be uploaded. Safety filters
    apply to both the input video and the generated result.
    """

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "video": ("VIDEO",),
                "prompt": (
                    "STRING",
                    {
                        "multiline": True,
                        "placeholder": "Describe the edit, e.g. \"Make this video anime. Keep everything else the same.\"",
                    },
                ),
                "api_key": API_KEY_INPUT_SPEC,
            },
        }

    RETURN_TYPES = ("VIDEO", "STRING")
    RETURN_NAMES = ("video", "video_url")
    FUNCTION = "edit"
    DESCRIPTION = (
        "Edit a video using Google Gemini Omni Flash on fal.ai. Describe the "
        "change in a simple instruction - keep prompts short and add \"Keep "
        "everything else the same\" to preserve the rest of the scene. "
        "Connect a LoadVideo node in and a SaveVideo/PreviewVideo node out."
    )

    def process_video_result(self, result):
        """Process the video result from the API."""
        if "video" not in result or not result["video"]:
            raise RuntimeError("No video was generated by the API.")

        video_info = result["video"]
        if not isinstance(video_info, dict):
            raise RuntimeError("Invalid video format in response")

        video_url = video_info.get("url")
        if not video_url:
            raise RuntimeError("No video URL found in response")

        return video_url

    def prepare_arguments(self, video_url, prompt):
        if not prompt or not prompt.strip():
            raise ValueError("prompt is required for Gemini Omni Flash editing")

        return {
            "video_url": video_url,
            "prompt": prompt.strip(),
        }

    def edit(self, video, prompt, api_key):
        try:
            client = self.get_client(api_key)
            video_url = self.upload_video(client, video)
            arguments = self.prepare_arguments(video_url, prompt)

            logger.info(f"Editing video with Gemini Omni Flash: {video_url}")

            result = self.call_api(client, "google/gemini-omni-flash/edit", arguments)

            edited_video_url = self.process_video_result(result)
            edited_video = self.download_video(edited_video_url)
            return (edited_video, edited_video_url)

        except Exception as e:
            logger.error(f"Gemini Omni Flash edit failed: {str(e)}")
            raise RuntimeError(f"Gemini Omni Flash edit failed: {str(e)}") from e
