import logging
from .base_node import (
    SupersideFalNode,
    ImageProcessingMixin,
    APIClientMixin,
    API_KEY_INPUT_SPEC,
)

logger = logging.getLogger(__name__)


class SupersideKling21ImageToVideoNode(
    SupersideFalNode,
    ImageProcessingMixin,
    APIClientMixin,
):
    """
    Kling 2.1 Image-to-Video Node: Generate high-quality videos from images
    using Kling 2.1 models via fal.ai API.

    This node supports three quality tiers: Master (premium), Pro (professional),
    and Standard (cost-efficient), each optimized for different use cases.
    """

    MODEL_ENDPOINTS = {
        "master": "fal-ai/kling-video/v2.1/master/image-to-video",
        "pro": "fal-ai/kling-video/v2.1/pro/image-to-video",
        "standard": "fal-ai/kling-video/v2.1/standard/image-to-video",
    }

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "prompt": (
                    "STRING",
                    {
                        "multiline": True,
                        "placeholder": "Enter your video prompt here",
                    },
                ),
                "image": ("IMAGE",),
                "model_tier": (
                    ["master", "pro", "standard"],
                    {
                        "default": "pro",
                        "tooltip": "Master: Premium quality "
                        "| Pro: Professional-grade | Standard: Cost-efficient",
                    },
                ),
                "api_key": API_KEY_INPUT_SPEC,
            },
            "optional": {
                "tail_image": (
                    "IMAGE",
                    {
                        "tooltip": "End frame image (Pro model only)",
                    },
                ),
                "duration": (
                    ["5", "10"],
                    {"default": "5"},
                ),
                "negative_prompt": (
                    "STRING",
                    {
                        "multiline": True,
                        "default": "blur, distort, and low quality",
                        "placeholder": "Content to avoid",
                    },
                ),
                "cfg_scale": (
                    "FLOAT",
                    {
                        "default": 0.5,
                        "min": 0.0,
                        "max": 1.0,
                        "step": 0.01,
                        "tooltip": "Classifier Free Guidance "
                        "scale - how closely to follow the prompt",
                    },
                ),
            },
        }

    RETURN_TYPES = ("STRING",)
    FUNCTION = "generate"
    DESCRIPTION = (
        "Generate high-quality videos from images using Kling 2.1. "
        "Choose between Master (premium), Pro (professional), "
        "or Standard (cost-efficient) tiers."
    )

    def process_video_result(self, result):
        """Process the video result from the API."""
        if "video" not in result or not result["video"]:
            raise RuntimeError("No video was generated by the API.")

        try:
            video_info = result["video"]
            logger.debug(f"Processing video: {video_info}")

            if not isinstance(video_info, dict):
                raise RuntimeError("Invalid video format in response")

            video_url = video_info.get("url")
            if not video_url:
                raise RuntimeError("No video URL found in response")

            return video_url

        except Exception as e:
            logger.error(f"Failed to process video: {str(e)}")
            raise

    def prepare_arguments(self, client, prompt, model_tier, **kwargs):
        """Prepare arguments for the Kling 2.1 API call."""
        image_url = self.upload_image(client, kwargs.get("image"))
        logger.info(f"Image uploaded successfully: {image_url}")

        arguments = {
            "prompt": prompt,
            "image_url": image_url,
        }

        if (
            "tail_image" in kwargs
            and kwargs["tail_image"] is not None
            and model_tier == "pro"
        ):
            tail_image_url = self.upload_image(client, kwargs["tail_image"])
            arguments["tail_image_url"] = tail_image_url
            logger.info(f"Tail image uploaded successfully: {tail_image_url}")

        if "duration" in kwargs and kwargs["duration"] is not None:
            arguments["duration"] = kwargs["duration"]

        if "negative_prompt" in kwargs and kwargs["negative_prompt"]:
            arguments["negative_prompt"] = kwargs["negative_prompt"]

        if "cfg_scale" in kwargs and kwargs["cfg_scale"] is not None:
            arguments["cfg_scale"] = kwargs["cfg_scale"]

        logger.debug(f"Prepared API arguments: {arguments}")
        return arguments

    def generate(self, prompt, model_tier, api_key, **kwargs):
        """Main generation function for Kling 2.1 video generation."""
        try:
            client = self.get_client(api_key)

            if model_tier not in self.MODEL_ENDPOINTS:
                raise ValueError(
                    f"Invalid model tier: {model_tier}. "
                    f"Must be one of: {list(self.MODEL_ENDPOINTS.keys())}"
                )

            endpoint = self.MODEL_ENDPOINTS[model_tier]
            arguments = self.prepare_arguments(client, prompt, model_tier, **kwargs)

            logger.info(
                f"Starting Kling 2.1 ({model_tier}) "
                f"video generation with prompt: '{prompt}'"
            )

            result = self.call_api(client, endpoint, arguments)

            logger.debug(f"Kling 2.1 ({model_tier}) API response: {result}")

            video_url = self.process_video_result(result)
            return (video_url,)

        except Exception as e:
            logger.error(f"Kling 2.1 ({model_tier}) video generation failed: {str(e)}")
            raise RuntimeError(f"Video generation failed: {str(e)}") from e
