import logging
from .base_node import (
    SupersideFalNode,
    ImageProcessingMixin,
    APIClientMixin,
    API_KEY_INPUT_SPEC,
)

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)


class SupersideSeedanceLiteImageToVideoNode(
    SupersideFalNode, ImageProcessingMixin, APIClientMixin
):
    """
    Seedance Lite Image-to-Video Node: Generate videos from reference images
    using Seedance Lite model via fal.ai API.
    """

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "prompt": (
                    "STRING",
                    {
                        "multiline": True,
                        "default": "The girl catches the puppy and hugs it.",
                        "placeholder": "Enter your prompt here",
                    },
                ),
                "reference_image_1": ("IMAGE",),
                "api_key": API_KEY_INPUT_SPEC,
            },
            "optional": {
                "reference_image_2": ("IMAGE",),
                "reference_image_3": ("IMAGE",),
                "reference_image_4": ("IMAGE",),
                "aspect_ratio": (
                    ["auto", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"],
                    {"default": "auto"},
                ),
                "resolution": (
                    ["480p", "720p"],
                    {"default": "720p"},
                ),
                "duration": (
                    ["3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
                    {"default": "5"},
                ),
                "camera_fixed": (
                    "BOOLEAN",
                    {
                        "default": False,
                    },
                ),
                "seed": ("INT", {"min": -1, "max": 0xFFFFFFFFFFFFFFFF}),
                "enable_safety_checker": (
                    "BOOLEAN",
                    {
                        "default": True,
                    },
                ),
            },
        }

    RETURN_TYPES = ("STRING",)
    FUNCTION = "generate"
    DESCRIPTION = "Generate videos from 1-4 reference images using Seedance Lite model"

    def prepare_reference_image_urls(self, client, **kwargs):
        """Prepare list of reference image URLs from input images."""
        reference_urls = []

        # Check for up to 4 reference images
        for i in range(1, 5):
            image_key = f"reference_image_{i}"
            if image_key in kwargs and kwargs[image_key] is not None:
                try:
                    url = self.upload_image(client, kwargs[image_key])
                    reference_urls.append(url)
                except Exception as e:
                    logger.warning(f"Failed to upload {image_key}: {str(e)}")
                    continue

        return reference_urls

    def prepare_arguments(self, client, prompt, **kwargs):
        """Prepare arguments for the API call."""
        # Get reference image URLs
        reference_urls = self.prepare_reference_image_urls(client, **kwargs)

        if not reference_urls:
            raise ValueError(
                "At least one reference image is required for Seedance Lite "
                "video generation"
            )

        arguments = {
            "prompt": prompt,
            "reference_image_urls": reference_urls,
        }

        # Add optional parameters if provided
        if "aspect_ratio" in kwargs and kwargs["aspect_ratio"] is not None:
            arguments["aspect_ratio"] = kwargs["aspect_ratio"]

        if "resolution" in kwargs and kwargs["resolution"] is not None:
            arguments["resolution"] = kwargs["resolution"]

        if "duration" in kwargs and kwargs["duration"] is not None:
            arguments["duration"] = kwargs["duration"]

        if "camera_fixed" in kwargs and kwargs["camera_fixed"] is not None:
            arguments["camera_fixed"] = kwargs["camera_fixed"]

        if kwargs.get("seed") and kwargs["seed"] != -1:
            arguments["seed"] = kwargs["seed"]

        if (
            "enable_safety_checker" in kwargs
            and kwargs["enable_safety_checker"] is not None
        ):
            arguments["enable_safety_checker"] = kwargs["enable_safety_checker"]

        return arguments

    def process_video_result(self, result):
        """Process the video result from the API."""
        if "video" not in result or not result["video"]:
            raise RuntimeError("No video was generated by the API.")

        try:
            video_info = result["video"]
            logger.debug(f"Processing video: {video_info}")

            if not isinstance(video_info, dict):
                raise RuntimeError("Invalid video format in response")

            video_url = video_info.get("url")
            if not video_url:
                raise RuntimeError("No video URL found in response")

            # Return video URL only (same as Pro version)
            return video_url

        except Exception as e:
            logger.error(f"Failed to process video: {str(e)}")
            raise

    def generate(self, prompt, api_key, **kwargs):
        """Main generation function."""
        try:
            client = self.get_client(api_key)
            arguments = self.prepare_arguments(client, prompt, **kwargs)
            logger.info(f"Calling Seedance Lite API with arguments: {arguments}")

            result = self.call_api(
                client, "fal-ai/bytedance/seedance/v1/lite/reference-to-video", arguments
            )

            logger.debug(f"API Response: {result}")

            # Process the video result
            video_url = self.process_video_result(result)
            return (video_url,)

        except Exception as e:
            logger.error(f"Generation failed: {str(e)}")
            raise
