import logging
from .base_node import (
    SupersideFalNode,
    APIClientMixin,
    VideoProcessingMixin,
    API_KEY_INPUT_SPEC,
)

logger = logging.getLogger(__name__)


class SupersideSeedVRUpscaleVideoNode(
    SupersideFalNode,
    VideoProcessingMixin,
    APIClientMixin,
):
    """
    SeedVR Upscale Video Node: Upscale videos using SeedVR2
    with temporal consistency via fal.ai API.

    This node provides high-quality video upscaling while
    maintaining temporal consistency across frames, ideal
    for enhancing video quality.
    """

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "video": ("VIDEO",),
                "api_key": API_KEY_INPUT_SPEC,
            },
            "optional": {
                "upscale_factor": (
                    "FLOAT",
                    {
                        "default": 2.0,
                        "min": 1.0,
                        "max": 10.0,
                        "step": 0.5,
                        "display": "slider",
                        "tooltip": "Multiply video dimensions by this factor",
                    },
                ),
                "seed": (
                    "INT",
                    {
                        "min": 0,
                        "max": 0xFFFFFFFFFFFFFFFF,
                        "tooltip": "Random seed for reproducibility",
                    },
                ),
            },
        }

    RETURN_TYPES = ("VIDEO", "STRING")
    RETURN_NAMES = ("video", "video_url")
    FUNCTION = "upscale"
    DESCRIPTION = (
        "Upscale videos using SeedVR2 with temporal consistency. "
        "Maintains smooth motion across frames while enhancing quality. "
        "Connect a LoadVideo node in and a SaveVideo/PreviewVideo node out."
    )

    def process_video_result(self, result):
        """Process the video result from the API."""
        if "video" not in result or not result["video"]:
            raise RuntimeError("No video was generated by the API.")

        try:
            video_info = result["video"]
            logger.debug(f"Processing video: {video_info}")

            if not isinstance(video_info, dict):
                raise RuntimeError("Invalid video format in response")

            video_url = video_info.get("url")
            if not video_url:
                raise RuntimeError("No video URL found in response")

            return video_url

        except Exception as e:
            logger.error(f"Failed to process video: {str(e)}")
            raise

    def prepare_arguments(self, video_url, **kwargs):
        """Prepare arguments for the SeedVR video upscale API call."""
        arguments = {
            "video_url": video_url,
        }

        if "upscale_factor" in kwargs and kwargs["upscale_factor"] is not None:
            arguments["upscale_factor"] = kwargs["upscale_factor"]

        if kwargs.get("seed") and kwargs["seed"] != 0:
            arguments["seed"] = kwargs["seed"]

        logger.debug(f"Prepared API arguments: {arguments}")
        return arguments

    def upscale(self, video, api_key, **kwargs):
        """Main upscaling function for SeedVR video."""
        try:
            client = self.get_client(api_key)
            video_url = self.upload_video(client, video)
            arguments = self.prepare_arguments(video_url, **kwargs)
            upscale_factor = kwargs.get("upscale_factor", 2.0)

            logger.info(
                f"Starting SeedVR video upscaling (factor: {upscale_factor}x) "
                f"for: {video_url}"
            )

            result = self.call_api(client, "fal-ai/seedvr/upscale/video", arguments)

            logger.debug(f"SeedVR video upscale API response: {result}")

            upscaled_video_url = self.process_video_result(result)
            upscaled_video = self.download_video(upscaled_video_url)
            return (upscaled_video, upscaled_video_url)

        except Exception as e:
            logger.error(f"SeedVR video upscaling failed: {str(e)}")
            raise RuntimeError(f"Video upscaling failed: {str(e)}") from e
