import logging
from .base_node import (
    SupersideFalNode,
    ImageProcessingMixin,
    APIClientMixin,
    API_KEY_INPUT_SPEC,
)

logger = logging.getLogger(__name__)


class Wan25ImageToVideoNode(
    SupersideFalNode,
    ImageProcessingMixin,
    APIClientMixin,
):
    """
    Wan 2.5 Image-to-Video Node: Generate high-quality videos from images
    using Wan 2.5 model via fal.ai API.

    This node provides advanced video generation capabilities with support for
    resolution settings, duration options, audio integration, and prompt expansion.
    """

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "prompt": (
                    "STRING",
                    {
                        "multiline": True,
                        "placeholder": "Enter your video prompt here "
                        "(max 800 characters)",
                    },
                ),
                "image": ("IMAGE",),
                "api_key": API_KEY_INPUT_SPEC,
            },
            "optional": {
                "audio_url": (
                    "STRING",
                    {
                        "default": "",
                        "placeholder": "URL of audio file (WAV/MP3, 3-30s, up to 15MB)",
                    },
                ),
                "resolution": (
                    ["480p", "720p", "1080p"],
                    {"default": "1080p"},
                ),
                "duration": (
                    ["5", "10"],
                    {"default": "5"},
                ),
                "negative_prompt": (
                    "STRING",
                    {
                        "multiline": True,
                        "default": "",
                        "placeholder": "Content to avoid (max 500 characters)",
                    },
                ),
                "enable_prompt_expansion": (
                    "BOOLEAN",
                    {
                        "default": True,
                        "tooltip": "Enable prompt rewriting using LLM "
                        "for better results",
                    },
                ),
                "seed": ("INT", {"min": 0, "max": 0xFFFFFFFFFFFFFFFF}),
            },
        }

    RETURN_TYPES = ("STRING",)
    FUNCTION = "generate"
    DESCRIPTION = (
        "Generate high-quality videos from images using Wan 2.5 model. "
        "Supports multiple resolutions, durations, audio integration, "
        "and prompt expansion."
    )

    def process_video_result(self, result):
        """Process the video result from the API."""
        if "video" not in result or not result["video"]:
            raise RuntimeError("No video was generated by the API.")

        try:
            video_info = result["video"]
            logger.debug(f"Processing video: {video_info}")

            if not isinstance(video_info, dict):
                raise RuntimeError("Invalid video format in response")

            video_url = video_info.get("url")
            if not video_url:
                raise RuntimeError("No video URL found in response")

            return video_url

        except Exception as e:
            logger.error(f"Failed to process video: {str(e)}")
            raise

    def prepare_arguments(self, client, prompt, **kwargs):
        """Prepare arguments for the Wan 2.5 API call."""
        image_url = self.upload_image(client, kwargs.get("image"))
        logger.info(f"Image uploaded successfully: {image_url}")

        arguments = {
            "prompt": prompt,
            "image_url": image_url,
        }

        audio_url = kwargs.get("audio_url", "").strip()
        if audio_url:
            arguments["audio_url"] = audio_url

        if "resolution" in kwargs and kwargs["resolution"] is not None:
            arguments["resolution"] = kwargs["resolution"]

        if "duration" in kwargs and kwargs["duration"] is not None:
            arguments["duration"] = kwargs["duration"]

        if "negative_prompt" in kwargs and kwargs["negative_prompt"]:
            arguments["negative_prompt"] = kwargs["negative_prompt"]

        if (
            "enable_prompt_expansion" in kwargs
            and kwargs["enable_prompt_expansion"] is not None
        ):
            arguments["enable_prompt_expansion"] = kwargs["enable_prompt_expansion"]

        if kwargs.get("seed") and kwargs["seed"] != 0:
            arguments["seed"] = kwargs["seed"]

        logger.debug(f"Prepared API arguments: {arguments}")
        return arguments

    def generate(self, prompt, api_key, **kwargs):
        """Main generation function for Wan 2.5 video generation."""
        try:
            client = self.get_client(api_key)
            arguments = self.prepare_arguments(client, prompt, **kwargs)
            logger.info(f"Starting Wan 2.5 video generation with prompt: '{prompt}'")

            result = self.call_api(client, "fal-ai/wan-25-preview/image-to-video", arguments)

            logger.debug(f"Wan 2.5 API response: {result}")

            video_url = self.process_video_result(result)
            return (video_url,)

        except Exception as e:
            logger.error(f"Wan 2.5 video generation failed: {str(e)}")
            raise RuntimeError(f"Video generation failed: {str(e)}") from e
